# Generated by Django 5.0.2 on 2024-02-20 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modelpath', models.FileField(upload_to='models/')),
                ('accuracy', models.FloatField()),
                ('categories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('predict_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('netmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impred.netmodels')),
            ],
            options={
                'unique_together': {('netmodel', 'predict_id')},
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('imagepath', models.ImageField(upload_to='images/')),
                ('predict', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='impred.labels')),
                ('netmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='impred.netmodels')),
            ],
        ),
    ]
