# Generated by Django 5.0.2 on 2024-02-11 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impred', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='predictname',
        ),
        migrations.AddField(
            model_name='images',
            name='netmodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='impred.netmodels'),
        ),
        migrations.AddField(
            model_name='images',
            name='predict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='impred.labels'),
        ),
    ]
