# Generated by Django 5.0.2 on 2024-02-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impred', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netmodels',
            name='version',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
