# Generated by Django 5.0.2 on 2024-02-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impred', '0002_remove_images_predictname_images_netmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='imagepath',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='netmodels',
            name='modelpath',
            field=models.FileField(upload_to='models/'),
        ),
    ]
