# Generated by Django 5.0.2 on 2024-02-14 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impred', '0003_alter_images_imagepath_alter_netmodels_modelpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='user',
        ),
    ]
