# Generated by Django 5.0.2 on 2024-02-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impred', '0004_remove_images_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netmodels',
            name='modelpath',
            field=models.FileField(upload_to='data/'),
        ),
    ]
