# Generated by Django 5.0.2 on 2024-02-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impred', '0004_remove_images_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labels',
            unique_together={('netmodel', 'predict_id')},
        ),
    ]
