# Generated by Django 5.0.2 on 2024-02-18 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impred', '0005_alter_netmodels_modelpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='netmodel',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='impred.netmodels'),
        ),
    ]
