# Generated by Django 5.0.2 on 2024-02-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impred', '0005_alter_labels_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='netmodels',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
    ]
