# Generated by Django 5.0.2 on 2024-02-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impred', '0006_netmodels_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='netmodels',
            name='categories',
            field=models.IntegerField(null=True),
        ),
    ]
