# Generated by Django 5.0.2 on 2024-02-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impred', '0006_alter_images_netmodel'),
        ('impred', '0008_alter_netmodels_accuracy_alter_netmodels_categories'),
    ]

    operations = [
    ]
