# Generated by Django 5.0.2 on 2024-02-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impred', '0008_alter_netmodels_accuracy_alter_netmodels_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='netmodels',
            name='version',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
