# Generated by Django 5.0.2 on 2024-02-29 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impred', '0009_netmodels_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='real',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='predict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='impred.labels'),
        ),
    ]
