name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV
          
      - name: Update poetry lock file
        run: poetry lock
        working-directory: ./impred

      - name: Install dependencies
        working-directory: ./impred
        run: poetry install
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 18.185.184.100 >> ~/.ssh/known_hosts

      - name: Deploy to remote server
        run: |
          scp -r ./impred/* ubuntu@18.185.184.100:/home/ubuntu

      - name: Apply Migrations
        working-directory: ./impred
        run: poetry run python manage.py migrate

      # - name: Collect Static Files
      #   run: poetry run python manage.py collectstatic --noinput

      - name: Start Django Server
        working-directory: ./impred
        run: poetry run python manage.py runserver 0.0.0.0:8000
